

GET http://localhost:8000/api/reviews

###
POST http://localhost:8000/api/contact

{
  "name": "John Doe",
  "email": "jontexjesus@gmail.com",
  "message": "This is a test message",
  "phone": "08012345678",
  "subject": "Test Subject"

}

